project/play/urls.py
from django.urls import path, include
from .views import *

app_name = "play"

urlpatterns = [
    ## services urls
    path('', rentListView.as_view(), name='rent_list',),
    path('create/', rentCreateView.as_view(), name='rent_create'),
    path('<int:pk>/update/', rentUpdateView.as_view(), name='rent_update'),
    # path('delete/<int:pk>', ServiceDeleteView.as_view(), name='rent_delete'),

    ##  RENT ORDERS URLS 
    path('rent/<int:pk>/orders/', rentOrderListView.as_view(), name='rent_order_list',),
    path('rent/orders/create/', rentOrderCreatView.as_view(), name='rent_order_create'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('play/', include('play.urls')),
]

project/play/models.py
import datetime
from django.utils.timezone import now
from django.template.defaultfilters import slugify
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class TimeStampMixin(models.Model):
    is_deleted      = models.BooleanField (default=False)
    created_at      = models.DateTimeField(auto_now_add=True,null=True)
    updated_at      = models.DateTimeField(auto_now=True,null=True)

    class Meta:
        abstract = True

    def __str__(self):
        if hasattr(self, 'number'):
            if self.number != None:
                return 'جهاز رقم :' + str(self.number)
            else:
                return str("object")
            # return self.name
        elif hasattr(self, 'rent'):
            return str(self.id)
        elif hasattr(self, 'device'):
            return str(self.id)
        else:
            return str(self.id)



class Device(TimeStampMixin,models.Model):
    KIND = (
        ('P3','بلايستيشن 3'),
        ('P4','بلايستيشن 4'),
        ('P5','بلايستيشن 5')
    )
    number      = models.SmallIntegerField(null=True, blank=True)
    kind        = models.CharField(max_length=2, choices=KIND, default='P4',null=True, blank=True)
    price       = models.SmallIntegerField(null=True, blank=True, verbose_name='سعر ساعة الحجز', default=30)
    place       = models.CharField(max_length=50, null=True, blank=True)
    notes       = models.CharField(max_length=250,null=True, blank=True)
    available   = models.BooleanField(default=True, null=True, blank=True) 

class Rent(TimeStampMixin, models.Model):
    device          = models.ForeignKey('Device', on_delete=models.CASCADE, null=True, blank=True)
    duration        = models.IntegerField(null=True, blank=True, verbose_name='مدة الحجز بالدقائق')
    created_by      = models.ForeignKey(User, on_delete=models.CASCADE)
    endTime         = models.DateTimeField(null=True, blank=True)

    def save(self, *args, **kwargs):
            if (self.duration is not None or self.duration != 0) and self.created_at is not None:
                duration_in_minutes = datetime.timedelta(minutes=self.duration)
                self.endTime = self.created_at + duration_in_minutes
            super().save(*args, **kwargs)

class Order(TimeStampMixin, models.Model):
    rent    = models.ForeignKey('Rent', on_delete=models.CASCADE, null=True, blank=True)
    name    = models.CharField(max_length=75 ,null=True, blank=True, verbose_name='الطلب')
    amount = models.SmallIntegerField(null=True, blank=True, verbose_name='العدد')
    price   = models.IntegerField(null=True, blank=True, verbose_name='السعر')
    created_by      = models.ForeignKey(User, on_delete=models.CASCADE)
   

project/play/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field, Submit, HTML
from .models import Device, Rent, Order
from django.contrib.auth.models import User
import datetime
from django.utils import timezone



class RentForm(forms.ModelForm):
    device = forms.ModelChoiceField(queryset=Device.objects.all(), label='الجهاز')
    duration = forms.IntegerField(label='المدة المحجوزة (بالدقائق) / 0 - مفتوح')
    created_by = forms.ModelChoiceField(queryset=User.objects.all(), label='تم الحجز بواسطة')

    class Meta:
        model = Rent
        fields = ['device', 'duration']
        labels = {
            'device': 'رقم الجهاز',
            'duration': 'مدة الحجز بالدقائق / 0 - مفتوح',
            'created_by': 'تم الحجز بواسطة'
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = kwargs.pop('user', None)
        self.helper = FormHelper()
        self.helper.form_method = 'post'


        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

        if self.user:
            self.initial['created_by'] = self.user.username
    
    def save(self, commit=True):
        rent = super().save(commit=False)
        self.created_at = timezone.now()
        if self.cleaned_data['duration'] != 0:
            rent.endTime =  self.created_at + datetime.timedelta(minutes=self.cleaned_data['duration'])
        if commit:
            rent.save()
        return rent

class OrderForm(forms.ModelForm):
    rent     = forms.ModelChoiceField(queryset=Rent.objects.all(), widget=forms.Select(), label='الحجز')
    name     = forms.CharField(widget=forms.TextInput, label='اسم الصنف')
    amount   = forms.IntegerField(widget=forms.NumberInput(), label='العدد')
    price    = forms.IntegerField(widget=forms.NumberInput(), label='اجمالى السعر')
    
    class Meta:
        model = Order
        fields = ['rent', 'name', 'amount', 'price']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.user = kwargs.pop('user', None)
        self.helper.layout = Layout(
            Field('rent'),
            Field('name'),
            Field('amount'),
            Field('price'),
        )

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

        if self.user:
            self.initial['created_by'] = self.user.username

    def save(self, commit=True):
        order = super().save(commit=False)
        if commit:
            order.save()
        return order

project/play/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from .models import *
from .forms import *
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q, F
from django.utils import timezone

class rentOrderCreatView(LoginRequiredMixin, CreateView):
    models          = Order
    template_name   = 'play/rent_order_create.html'
    form_class      = OrderForm

    def form_valid(self, form):
            form.instance.created_by = self.request.user
            return super().form_valid(form)
            
    def get_success_url(self):
        rent = self.object.rent
        return reverse_lazy('play:rent_order_list', kwargs={'pk': rent.id})

class rentOrderListView(LoginRequiredMixin, ListView):
    model = Order
    template_name = 'play/rent_order_list.html'
    context_object_name = 'orders'

    def get_queryset(self):
        pk = self.kwargs.get('pk')
        return Order.objects.filter(rent__pk=pk)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)    
        rentId = self.kwargs.get('pk')
        device = Rent.objects.get(pk=rentId).device
        context['device'] = device
        orders = Order.objects.filter(rent__pk=rentId)
        total_price = sum(order.price for order in orders)
        context['total_price'] = total_price
        return context
    

class rentUpdateView(LoginRequiredMixin, UpdateView):
    model           = Rent
    form_class      = RentForm
    success_url     = reverse_lazy('play:rent_list')
    template_name   =  'play/rent_create_form.html'

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)

class rentCreateView(LoginRequiredMixin, CreateView):
    model = Rent
    form_class = RentForm
    success_url = reverse_lazy('play:rent_list')
    template_name = 'play/rent_create_form.html'

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)


class rentListView(LoginRequiredMixin, ListView):   
    model = Rent
    template_name = 'play/rent_list.html'
    context_object_name = 'rents'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(is_deleted=False).order_by(F('created_at').desc())
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)    
        devices = Device.objects.all()
        context['devices'] = devices
        current_time = timezone.now()
        context['current_time'] = current_time
        return context

project/play/templates/play/index.html
<!DOCTYPE html>
<html lang="ar">
<head>
	<!-- Add additional CSS in static file -->
  {% load static %}
  {% block title %}{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" />
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <style>
    
  {% block style %}
  {% endblock %}
  </style>
</head>
<body>
	<div class="container-fluid text-right" dir="rtl">
	    <div class="row">
	        <div class="col-12">
	            <div class="float-right p-2 m-2">
	                <img style="width: 8rem;" class="" src="https://cdn.pixabay.com/photo/2017/01/30/21/01/kontroller-2022084_1280.png" >
	            </div>
	            <div class="float-left">
	                <div class="dropdown">
                        <button class="btn dropdown-toggle" style="" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-user-circle fa-2x text-danger" aria-hidden="true"></i>
                        </button>
                        <div class="dropdown-menu bg-dark text-right text-white" aria-labelledby="dropdownMenuButton">
                            <h5 class="bg-primary text-white">مرحبا {{request.user.get_short_name}}</h5>
                            <a class="dropdown-item text-white" href="#">الملف الشخصى</a>
                            <a class="dropdown-item text-white" href="#">الاشعارات</a>
                            <a class="dropdown-item text-white" href="/cAccounts/logout">تسجيل الخروج</a>
                        </div>
                    </div>
	            </div>
	        </div>
	    </div>
	<!-- -- -->
    	<div class="row" style="height:79vh">
    	    <div class="col-2 p-3 text-white" style="background-color:#30393D; position: fixed; z-index:2">

                <a href="/play/" class="">
                    <button class="btn btn-secondary w-100 m-2 text-right btn-custom">قائمة الأجهزة </button>
                </a>

                <a href="/play/create" class="">
                    <button class="btn btn-secondary w-100 m-2 text-right btn-custom">اضافة حجز جديد</button>
                </a>

    	    </div>
    	    <div class="col-10">
                {% block content %}{% endblock %}
    	    </div>
    	</div>

	</div>

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>{% block script %}{% endblock %}</script>
    <script>
    </script>
</body>
</html>

project/play/templates/play/rent_create_form.html
{% extends "play/index.html" %}
{% load crispy_forms_tags %} 
{% block title %}
    <title>عمل حجز جديد</title>
{% endblock %}

{% block style %}

{% endblock %}

{% block content %}
<div class="container-fluid" style="position: relative;right: 20%;">
    <div class="row mt-5 mb-3">
        <div class="col-10 m-auto">
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-primary">حفظ</button>
            </form>
            
        </div>
    </div>
</div>
{% endblock %}

{% block script %}

{% endblock %}

project/play/templates/play/rent_list.html
{% extends "play/index.html" %}
{% block title %}
    <title>قائمة الحجز</title>
{% endblock %}

{% block style %}
.card-success:hover{
    background-color:#28a745 !important;
}

.card-danger:hover{
    background-color:#dc3545!important
}
{% endblock %}

{% block content %}
<div class="container-fluid" style="position: relative;right: 20%;">
    <div class="row mt-5 mb-3">
        {% for device in devices %}
        {%if device.available == True%}
        <div class="card card-success border-success mb-3 text-center m-2" style="max-width: 18rem;">
            <div class="card-header h3">جهاز رقم  {{device.number}}</div>
            <div class="card-body">
                <img class="card-img-top" src="https://cdn.pixabay.com/photo/2020/04/15/20/48/controller-5048157_640.png" alt="Card image cap">
                <h5 class="card-title border p-2 m-2 h3 bg-white">
                    <p class="p-2 text-success">الجهاز متاح</p>
                    <a class="btn btn-primary d-block w-100 text-white p-2 m-2">حجز الجهاز</a>
                </h5>
            </div>
        </div>
        {%elif device.available == False%}
        {% with rent=device.rent_set.last %}
        <div class="card card-danger border-danger mb-3 text-center m-2" style="max-width: 18rem;">
            <div class="card-header h3">جهاز رقم  {{device.number}}</div>
            <div class="card-body text-danger">
                <img class="card-img-top" src="https://cdn.pixabay.com/photo/2020/04/15/20/48/controller-5048157_640.png" alt="Card image cap">
                {%if rent.endTime > current_time%}
                <h5 class="card-title border p-2 m-2 h3 bg-white">
                    <p class="p-1 text-danger">
                        {% if rent.endTime > rent.created_at%}
                            <p class="p-0 text-danger">الحجز ينتهى {{ rent.endTime|date:"M. j, Y, h:i A"}}</p>
                        {% elif rent.endTime == rent.created_at %}
                            <p class="text-primary">الحجز مفتوح الوقت</p>
                            <a class="btn btn-warning d-block w-100 text-white p-2 m-2">تعديل الحجز بوقت</a>
                        {% endif %}
                    </p>
                    <a class="btn btn-warning d-block w-100 text-white p-2 m-2" href="{% url 'play:rent_update' pk=rent.pk %}">تعديل الحجز</a>
                    <a class="btn btn-info d-block w-100 text-white p-2 m-2">انهاء الحجز</a>
                    <a class="btn btn-success d-block w-100 text-white p-2 m-2" href="{% url 'play:rent_order_list' pk=rent.pk %}"> طلبات الحجز</a>
                </h5>
                {%else%}
                <p class="p-1">
                    <p class="text-info">
                        <span>وقت الانتهاء : {{ rent.endTime|date:"h:i A" }}</span><br>
                        <span>الوقت حاليا :   {% now "h:i A" %} </span>
                    </p>
                    <p class="bg-danger d-block w-100 text-white"> انتهاء موعد الحجز برجاء  إنهاء الحجز</p>
                    <a href="" class="btn btn-info d-block w-100"> إنهاء الحجز</a>
                </p>
                {%endif%}
                
            </div>
        </div>
        {%endwith%}
        {%endif%}        
        {% endfor %}
    </div>
</div>
{% endblock %}

{% block script %}

{% endblock %}

project/play/templates/play/rent_order_create.html
{% extends "play/index.html" %}
{% load crispy_forms_tags %} 
{% block title %}
    <title>عمل حجز جديد</title>
{% endblock %}

{% block style %}

{% endblock %}

{% block content %}
<div class="container-fluid" style="position: relative;right: 20%;">
    <div class="row mt-5 mb-3">
        <div class="col-10 m-auto">
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-primary">حفظ</button>
            </form>
            
        </div>
    </div>
</div>
{% endblock %}

{% block script %}

{% endblock %}

project/play/templates/play/rent_order_list.html
{% extends "play/index.html" %}
{% block title %}
    <title>قائمة طلبات الحجز</title>
{% endblock %}

{% block style %}

{% endblock %}

{% block content %}
<div class="container-fluid" style="position: relative;right: 20%;">
    <h3 class="text-center">قائمة بطلبات حجز <span>{{device}}</span></h3>
    <div class="row">
        <div class="col-4">
            <a class="d-block btn btn-primary" href="{% url 'play:rent_order_create' %}">اضافة طلب جديد للحجز</a>
        </div>
        <div class="col-4 mr-auto">
            <a class="d-block btn btn-info" href="{% url 'play:rent_list' %}">قائمة الأجهزة</a>
        </div>
    </div>
    <div class="row mt-5 mb-3">
        <div class="col-10 m-auto h6">
            <table class="table table-bordered  text-center table-striped table-hover">
                <thead class="h5 thead-dark">
                        <th>الطلب</th>
                        <th>العدد</th>
                        <th>السعر</th>
                        <th>اوامر</th>
                </thead>
                <tbody>
                    {%for order in orders%}
                    <tr class="">
                        <td>{{order.name}}</td>
                        <td>{{order.amount}}</td>
                        <td>{{order.price}}</td>
                        <td class="text-white">
                            <a class="btn btn-info w-50">تعديل الطلب</a>
                            <a class="btn btn-danger mr-5">حذف الطلب</a>
                        </td>
                    </tr>
                    {%endfor%}
                </tbody>
            </table>
        </div>
        <div class="col-4 mr-auto h3 p-2 mt-4">
            <span class="display:inline-block border border-top p-3 m-2">إجمالى المبلغ : {{total_price }}</span>
        </div>

    </div>
</div>
{% endblock %}

{% block script %}

{% endblock %}